### ISSUE TITLE
Bug: unable to verify email address ("403 Invalid Signature") 

### ISSUE THREAD

**Issue by ckjzam** [caendesilva/mutual-aid-app#37] opened 2022-07-30 21:04 UTC
Hi, I've never used github so I don't know if I'm doing this right.

I just signed up and I'm trying to verify my email address. I clicked the link and got a blank page that just says 403 | INVALID SIGNATURE and I still get asked to verify my email when I go to make a listing.

I tried pasting the URL in the email into a web browser and got the same result.

I clicked "resend verification email" and got a second email with a different URL, but that just got the same result again.

**Comment by caendesilva** [comment] 2022-07-31 07:50
Hey @ckjzam! Thank you so much for this bug report. You did a great job detailing it. We recently switched servers, so this may be related to that. So here's what I'm gonna do. I'm going to manually mark your email as verified so you can get started with the app while I take a deeper look and solve this issue. Let me know if you have any questions, and have a great day! Thank you once again for the bug report!

**Comment by caendesilva** [comment] 2022-07-31 08:23
The bug was caused by a an internal server misconfiguration and has been fixed. I've verified the fix works across subdomains. I'll make a report to the team on our secure internal channels. I'm going to close this issue now, but feel free to reopen or create a new one if you have any more issues. Thanks again!

**Closed by caendesilva** 2022-07-31 08:23 UTC
